### ISSUE TITLE
Licence statement in README

### ISSUE THREAD

**Issue by russel** [abingham/accu-2017-elm-app#25]
Although the GitHub control line says MIT, and there is a LICENSE.txt file, it is not immediately clear to someone alighting on the page what the licence is for this software – I think GitHub could do their licence display thing better. Perhaps adding a section in the README with a licence icon so that it is "hit people over the head" obvious might be helpful?

Or maybe I am worrying over nothing.

**Comment by abingham** [comment]
Good idea! I've added the badge.
