### ISSUE TITLE
Wrong days

### ISSUE THREAD

**Issue by russel** [abingham/accu-2017-elm-app#26]
Conference is Wednesday, Thursday, Friday, Saturday. Tuesday is workshops day. Currently the application gives the conference as Tuesday, Wednesday, Thursday, Friday.

**Comment by abingham** [comment]
Should be fixed in 806b482d33599cb7f581f28ae1ef4b72aa40a8b7

**Comment by russel** [comment]
Splendid, thanks.

Is there a deployment phase that has to be waited for, or is it continuous delivery from master HEAD?

Is there a way of knowing which version is running in the browser?

Will the code in the browser refresh to update the application?
