### ISSUE TITLE
Use the conference colour, maybe also the logo?

### ISSUE THREAD

**Issue by russel** [abingham/accu-2017-elm-app#29]
The ACCU 2017 conference colour is an orange, #ff5e00, might it be possible to use this to to create continuity and connection? Not a big issue though, the blue works well.

**Comment by abingham** [comment]
I've made an initial attempt at using the correct orange. You can [see it here](https://sixty-north.com/c/accu-2017-new-theme/). 

Honestly, I'm not 100% sure how to manipulate the colors. MDL makes it simple to use certain color combinations, but it's not clear to me how to use arbitrary colors. I'm sure it's possible to do through CSS, but I haven't looked too deeply into it.

**Comment by abingham** [comment]
Is there an official logo I can use? Just the header from the conference site? I should be able to put it in the header.

**Comment by russel** [comment]
I think having the orange head makes the connection. Perhaps treat colour of the session footers as a TBD/enhancement?

There is an official logo, downloading the PNG of the orange ACCU 2017 logo should give you it. If there are problems I can attach a copy of the PNG I use to create the site, which i think is effectively the master official version.

**Comment by abingham** [comment]
I've got the logo from the conference site; it looks like that'll work fine.

I can make the session footers orange as well, I think. I'll try to get that set up later today.

**Comment by abingham** [comment]
I got the logo in place, and I think the colors are looking pretty good now as well. So I'm going to close this out and we can deal with any details in separate issues.

**Comment by russel** [comment]
I think it looks really very good, and harmonious with the colours.

I see the issue with my assumption about the fixed columns, narrowing the width of the browser shows the fixed font and wrapping of the units. I haven't tried this on a phone, which  guess is the real target client. However this is for a different issue, This issue is closed. :-)
