### ISSUE TITLE
Trying to initialize the `ACCUSchedule` module with an unexpected flag.

### ISSUE THREAD

**Issue by rob-smallshire** [abingham/accu-2017-elm-app#47]
When I follow the installation instruction I get this error when I connect to the running application.

```
Oops! Something went wrong when starting your Elm program.

Trying to initialize the `ACCUSchedule` module with an unexpected flag.
I tried to convert it to an Elm value, but ran into this problem:

Expecting a String at _.apiBaseUrl but instead got: undefined
```

**Comment by rob-smallshire** [comment]
Ah, now I see this warning from the server:

```
15:27:39 client.1   |  WARNING in API_BASE_URL environment variable is undefined.
15:27:39 client.1   |  WARNING in ./~/opal-runtime/src/nodejs.js
```

I guess i need to set this environment variable to ... something.

**Comment by abingham** [comment]
I think this is because you haven't created a `.env` file. It's mentioned in the readme, but i could probably emphasise it more.

**Comment by rob-smallshire** [comment]
Right you are. I inadvertently skipped that bit.

**Comment by russel** [comment]
I feel it has to be said, I missed it as well.

**Comment by abingham** [comment]
I've created #48 to deal with this.
